<a href="https://colab.research.google.com/github/InowaR/frame/blob/main/2_2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [146]:
import numpy as np
import pandas as pd
b = np.array([1,2])
c = np.array([1,2])
a = np.array([1,2])
w = np.array([5,6,7,8])
b_tile = np.tile(b, 2)
b_repeat = np.repeat(b,2)
c_repeat = np.repeat(c, 2)
a_tile = np.tile(a,2)
print(b_tile, '<---- b')
print(c_repeat, '<---- c')
print(a_tile, '<---- a')
b_new = np.ones(len(b))
b_new = b_new - b
b_new = np.repeat(b_new, 2)
print(b_new, '<---- 1 - b')
print ('------------errors---------')
errors = np.array([10,20])
errors = np.repeat(errors, 2)
errors = pd.DataFrame(errors)
c_errors = pd.DataFrame(c_repeat)
ones = np.ones(len(w))
ones = pd.DataFrame(ones)
c_one = errors * c_errors * (ones - c_errors)
print(c_one)
c_new = np.split(c_repeat, 2)
c_weights = w * c_repeat
c_weights = np.split(c_weights, 2)
c_weights = pd.DataFrame(c_weights)
c_weights = c_weights.sum(axis=1)
c_weights.to_numpy()
c_weights = np.repeat(c_weights, 2)
c_w = c_weights.to_numpy()
print('---------Cw-------------')
c_w = pd.DataFrame(c_w)
print(c_w)
c_frame = c_one * c_w
print('---------[C2]-------------')
print(c_frame)

[1 2 1 2] <---- b
[1 1 2 2] <---- c
[1 2 1 2] <---- a
[ 0.  0. -1. -1.] <---- 1 - b
------------errors---------
      0
0   0.0
1   0.0
2 -40.0
3 -40.0
---------Cw-------------
    0
0  11
1  11
2  30
3  30
---------[C2]-------------
        0
0     0.0
1     0.0
2 -1200.0
3 -1200.0


In [149]:
b_tile = pd.DataFrame(b_tile)
print('--------[B1]--------')
print(b_tile)
c_repeat = pd.DataFrame(c_repeat)
print('--------[C1]--------')
print(c_repeat)
mul = c_repeat * b_tile
print('--------[B1] * [C1] = [5,6,7,8 weights] -------------')
print(mul)

--------[B1]--------
   0
0  1
1  2
2  1
3  2
--------[C1]--------
   0
0  1
1  1
2  2
3  2
--------[B1] * [C1] = [5,6,7,8 weights] -------------
   0
0  1
1  2
2  2
3  4


In [150]:
print ('------------errors---------')
errors = np.array([10,20])
errors = np.repeat(errors, 2)
errors = pd.DataFrame(errors)
print(errors)
print('----------------------------------------')
c_errors = pd.DataFrame(c_repeat)
print(c_errors)
print('----------------------------------------')
ones = np.ones(len(w))
ones = pd.DataFrame(ones)
print(ones)
print('----------------------------------------')
c_one = errors * c_errors * (ones - c_errors)
print(c_one)
print('----------------------------------------')

------------errors---------
    0
0  10
1  10
2  20
3  20
----------------------------------------
   0
0  1
1  1
2  2
3  2
----------------------------------------
     0
0  1.0
1  1.0
2  1.0
3  1.0
----------------------------------------
      0
0   0.0
1   0.0
2 -40.0
3 -40.0
----------------------------------------


In [151]:
a_tile = pd.DataFrame(a_tile)
print('--------[A2]--------')
print(a_tile)
b_repeat = pd.DataFrame(b_repeat)
b_new = pd.DataFrame(b_new)
b_mul = b_repeat * b_new
print('--------[B2]--------')
print(b_mul)
mul_second = a_tile * b_mul * c_frame
print('--------[A2] * [B2] * [C2] = [1,2,3,4 weights]--------')
print(mul_second)

--------[A2]--------
   0
0  1
1  2
2  1
3  2
--------[B2]--------
     0
0  0.0
1  0.0
2 -2.0
3 -2.0
--------[A2] * [B2] * [C2] = [1,2,3,4 weights]--------
        0
0     0.0
1     0.0
2  2400.0
3  4800.0


In [172]:
%%html 
<h2> --------------------------------- </h2>
<h2> [A1] * [B1] * [C1] = [w1] </h2>
<h2> [A2] * [B1] * [C1] = [w2] </h2>
<h2> [A1] * [B2] * [C2] = [w3] </h2>
<h2> [A2] * [B2] * [C2] = [w4] </h2>
<h2> --------------------------------- </h2>
<h2> [B1] * [C1] = [w5] </h2>
<h2> [B2] * [C1] = [w6] </h2>
<h2> [B1] * [C2] = [w7] </h2>
<h2> [B2] * [C2] = [w8] </h2>