<a href="https://colab.research.google.com/github/InowaR/frame/blob/main/3-2-3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import numpy as np
import pandas as pd
b = np.array([1,2])
c = np.array([1,2,3])
a = np.array([1,2,3])
w = np.array([7,8,9,10,11,12])
b_tile = np.tile(b, len(c))
b_repeat = np.repeat(b,len(a))
c_repeat = np.repeat(c, len(b))
a_tile = np.tile(a,len(b))
print('=======================================')
print(b_tile, '<---- b')
print(c_repeat, '<---- c')
print(a_tile, '<---- a')
b_new = np.ones(len(b))
b_new = b_new - b
b_new = np.repeat(b_new, len(a)) # number of inputs (a1,a2,a3)
print(b_new, '<---- 1 - b')
errors = np.array([1,2,3]) # number of outputs (c1,c2,c3)
errors = np.repeat(errors, len(b)) # number of hidden array (b1,b2)
errors = pd.DataFrame(errors)
c_errors = pd.DataFrame(c_repeat)
ones = np.ones(len(w))
ones = pd.DataFrame(ones)
c_one = errors * c_errors * (ones - c_errors)
c_new = np.split(c_repeat, len(c)) # number of outputs
c_weights = w * c_repeat
c_weights = np.split(c_weights, len(c)) # number of outputs
c_weights = pd.DataFrame(c_weights)
c_weights = c_weights.sum(axis=1)
c_weights.to_numpy()
c_weights = np.repeat(c_weights, len(b))
c_w = c_weights.to_numpy()
c_w = pd.DataFrame(c_w)
c_frame = c_one * c_w
print('---------[C2]-------------')
print(c_frame)

[1 2 1 2 1 2] <---- b
[1 1 2 2 3 3] <---- c
[1 2 3 1 2 3] <---- a
[ 0.  0.  0. -1. -1. -1.] <---- 1 - b
---------[C2]-------------
        0
0     0.0
1     0.0
2  -152.0
3  -152.0
4 -1242.0
5 -1242.0


In [35]:
b_tile = pd.DataFrame(b_tile)
print('--------[B1]--------')
print(b_tile)
c_repeat = pd.DataFrame(c_repeat)
print('--------[C1]--------')
print(c_repeat)
mul = c_repeat * b_tile
print('--------[B1] * [C1] = [7,8,9,10,11,12 weights] -------------')
print(mul)

--------[B1]--------
   0
0  1
1  2
2  1
3  2
4  1
5  2
--------[C1]--------
   0
0  1
1  1
2  2
3  2
4  3
5  3
--------[B1] * [C1] = [7,8,9,10,11,12 weights] -------------
   0
0  1
1  2
2  2
3  4
4  3
5  6


In [36]:
print ('------------errors---------')
errors = np.array([1,2,3])
errors = np.repeat(errors, len(b))
errors = pd.DataFrame(errors)
print(errors)
print('----------------------------------------')
c_errors = pd.DataFrame(c_repeat)
print(c_errors)
print('----------------------------------------')
ones = np.ones(len(w))
ones = pd.DataFrame(ones)
print(ones)
print('----------------------------------------')
c_one = errors * c_errors * (ones - c_errors)
print(c_one)
print('----------------------------------------')

------------errors---------
   0
0  1
1  1
2  2
3  2
4  3
5  3
----------------------------------------
   0
0  1
1  1
2  2
3  2
4  3
5  3
----------------------------------------
     0
0  1.0
1  1.0
2  1.0
3  1.0
4  1.0
5  1.0
----------------------------------------
      0
0   0.0
1   0.0
2  -4.0
3  -4.0
4 -18.0
5 -18.0
----------------------------------------


In [37]:
a_tile = pd.DataFrame(a_tile)
print('--------[A2]--------')
print(a_tile)
b_repeat = pd.DataFrame(b_repeat)
b_new = pd.DataFrame(b_new)
b_mul = b_repeat * b_new
print('--------[B2]--------')
print(b_mul)
mul_second = a_tile * b_mul * c_frame
print('--------[A2] * [B2] * [C2] = [1,2,3,4,5,6 weights]--------')
print(mul_second)

--------[A2]--------
   0
0  1
1  2
2  3
3  1
4  2
5  3
--------[B2]--------
     0
0  0.0
1  0.0
2  0.0
3 -2.0
4 -2.0
5 -2.0
--------[A2] * [B2] * [C2] = [1,2,3,4,5,6 weights]--------
        0
0     0.0
1     0.0
2    -0.0
3   304.0
4  4968.0
5  7452.0


In [30]:
%%html 
<h2> --------------------------------- </h2>
<h2> [A1] * [B1] * [C1] = [w1] </h2>
<h2> [A2] * [B1] * [C1] = [w2] </h2>
<h2> [A3] * [B1] * [C1] = [w3] </h2>
<h2> [A1] * [B2] * [C2] = [w4] </h2>
<h2> [A2] * [B2] * [C2] = [w5] </h2>
<h2> [A3] * [B1] * [C2] = [w6] </h2>
<h2> --------------------------------- </h2>
<h2> [B1] * [C1] = [w7] </h2>
<h2> [B2] * [C1] = [w8] </h2>
<h2> [B1] * [C2] = [w9] </h2>
<h2> [B2] * [C2] = [w10] </h2>
<h2> [B1] * [C3] = [w11] </h2>
<h2> [B2] * [C3] = [w12] </h2>