<a href="https://colab.research.google.com/github/InowaR/frame/blob/main/decart3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [76]:
import pandas as pd
import numpy as np
import random
a = np.array([2,4]) # number and value of inputs
b = np.array([1,2,3,4]) # number and value of outputs
w = np.array([len(a) * len(b)])
w = np.arange(1, w+1) 
w = np.random.randint(1, 10, len(a) * len(b)) # number and value of weights
w = w.reshape(len(b),len(a))
temp = np.tile(a,len(b))
temp = np.split(temp, len(b))
temp = np.vstack(temp)
frame_a = pd.DataFrame(temp.T)
frame_b = pd.DataFrame(b)
frame_w = pd.DataFrame(w.T)
print (frame_a) 
print("----------input----------------------")
print(frame_w)
print("----------weight---------------------")
a_mul = frame_a * frame_w
final = a_mul.sum(axis ='index')
print (final)
print("----------output---------------------")

   0  1  2  3
0  2  2  2  2
1  4  4  4  4
----------input----------------------
   0  1  2  3
0  2  3  3  2
1  7  7  4  7
----------weight---------------------
0    32
1    34
2    22
3    32
dtype: int64
----------output---------------------


In [77]:
temp2 = final
out_l = np.array([2,3,4,5])
temp3 = temp2.to_numpy()
print(temp3)
# end = np.array([1,1,1,1])
# was = np.array([len(ne) * len(end)])
# was = np.arange(1, was+1) 
# was = np.random.randint(1, 10, len(final_arr) * len(end)) # number and value of weights
# was = was.reshape(len(was),len(ne))
temp3 = np.tile(temp3, len(out_l))
temp3 = np.split(temp3, len(out_l))
temp3 = np.vstack(temp3)
print(temp3)
frame_inl = pd.DataFrame(temp3.T)
print(frame_inl)

[32 34 22 32]
[[32 34 22 32]
 [32 34 22 32]
 [32 34 22 32]
 [32 34 22 32]]
    0   1   2   3
0  32  32  32  32
1  34  34  34  34
2  22  22  22  22
3  32  32  32  32


In [ ]:
%%html
<a href="https://ibb.co/DKPHnYY"><img src="https://i.ibb.co/JkWwPqq/image.png" alt="image" border="0"></a>