<a href="https://colab.research.google.com/github/InowaR/frame/blob/main/sigmoid_errors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
import pandas as pd
b = np.array([0.534943,0.579324])
c = np.array([0.698027,0.631668,0.569739])
a = np.array([0.1,0.2,0.3])
w = np.array([0.7,0.8,0.9,0.1,0.2,0.3])
b_tile = np.tile(b, len(c))
b_repeat = np.repeat(b,len(a))
c_repeat = np.repeat(c, len(b))
a_tile = np.tile(a,len(b))
print('=======================================')
print(b_tile, '<---- b')
print(c_repeat, '<---- c')
print(a_tile, '<---- a')
b_new = np.ones(len(b))
b_new = b_new - b
b_new = np.repeat(b_new, len(a)) # number of inputs (a1,a2,a3)
print(b_new, '<---- 1 - b')
errors = np.array([0.098027,0.331668,0.469739]) # number of outputs (c1,c2,c3) - delta
errors = np.repeat(errors, len(b)) # number of hidden array (b1,b2)
errors = pd.DataFrame(errors)
c_errors = pd.DataFrame(c_repeat)
ones = np.ones(len(w))
ones = pd.DataFrame(ones)
c_one = errors * c_errors * (ones - c_errors)
c_new = np.split(c_repeat, len(c)) # number of outputs
c_weights = w * c_repeat
c_weights = np.split(c_weights, len(c)) # number of outputs
c_weights = pd.DataFrame(c_weights)
c_weights = c_weights.sum(axis=1)
c_weights.to_numpy()
c_weights = np.repeat(c_weights, len(b))
c_w = c_weights.to_numpy()
c_w = pd.DataFrame(c_w)
c_frame = c_one * c_w
print('---------[C2]-------------')
print(c_frame)

[0.534943 0.579324 0.534943 0.579324 0.534943 0.579324] <---- b
[0.698027 0.698027 0.631668 0.631668 0.569739 0.569739] <---- c
[0.1 0.2 0.3 0.1 0.2 0.3] <---- a
[0.465057 0.465057 0.465057 0.420676 0.420676 0.420676] <---- 1 - b
---------[C2]-------------
          0
0  0.021635
1  0.021635
2  0.048744
3  0.048744
4  0.032803
5  0.032803


In [10]:
b_tile = pd.DataFrame(b_tile)
print('--------[B1]--------')
print(b_tile)
c_repeat = pd.DataFrame(c_repeat)
print('--------[C1]--------')
print(c_repeat)
mul = c_repeat * b_tile
print('--------[B1] * [C1] = [7,8,9,10,11,12 weights] -------------')
print(mul)

--------[B1]--------
          0
0  0.534943
1  0.579324
2  0.534943
3  0.579324
4  0.534943
5  0.579324
--------[C1]--------
          0
0  0.698027
1  0.698027
2  0.631668
3  0.631668
4  0.569739
5  0.569739
--------[B1] * [C1] = [7,8,9,10,11,12 weights] -------------
          0
0  0.373405
1  0.404384
2  0.337906
3  0.365940
4  0.304778
5  0.330063


In [11]:
print ('------------errors---------')
errors = np.array([0.098027,0.331668,0.469739])
errors = np.repeat(errors, len(b))
errors = pd.DataFrame(errors)
print(errors)
print('----------------------------------------')
c_errors = pd.DataFrame(c_repeat)
print(c_errors)
print('----------------------------------------')
ones = np.ones(len(w))
ones = pd.DataFrame(ones)
print(ones)
print('----------------------------------------')
c_one = errors * c_errors * (ones - c_errors)
print(c_one)
print('----------------------------------------')

------------errors---------
          0
0  0.098027
1  0.098027
2  0.331668
3  0.331668
4  0.469739
5  0.469739
----------------------------------------
          0
0  0.698027
1  0.698027
2  0.631668
3  0.631668
4  0.569739
5  0.569739
----------------------------------------
     0
0  1.0
1  1.0
2  1.0
3  1.0
4  1.0
5  1.0
----------------------------------------
          0
0  0.020663
1  0.020663
2  0.077167
3  0.077167
4  0.115150
5  0.115150
----------------------------------------


In [12]:
a_tile = pd.DataFrame(a_tile)
print('--------[A2]--------')
print(a_tile)
b_repeat = pd.DataFrame(b_repeat)
b_new = pd.DataFrame(b_new)
b_mul = b_repeat * b_new
print('--------[B2]--------')
print(b_mul)
mul_second = a_tile * b_mul * c_frame
print('--------[A2] * [B2] * [C2] = [1,2,3,4,5,6 weights]--------')
print(mul_second)

--------[A2]--------
     0
0  0.1
1  0.2
2  0.3
3  0.1
4  0.2
5  0.3
--------[B2]--------
          0
0  0.248779
1  0.248779
2  0.248779
3  0.243708
4  0.243708
5  0.243708
--------[A2] * [B2] * [C2] = [1,2,3,4,5,6 weights]--------
          0
0  0.000538
1  0.001076
2  0.003638
3  0.001188
4  0.001599
5  0.002398


In [ ]:
%%html 
<h2> --------------------------------- </h2>
<h2> [A1] * [B1] * [C1] = [w1] </h2>
<h2> [A2] * [B1] * [C1] = [w2] </h2>
<h2> [A3] * [B1] * [C1] = [w3] </h2>
<h2> [A1] * [B2] * [C2] = [w4] </h2>
<h2> [A2] * [B2] * [C2] = [w5] </h2>
<h2> [A3] * [B1] * [C2] = [w6] </h2>
<h2> --------------------------------- </h2>
<h2> [B1] * [C1] = [w7] </h2>
<h2> [B2] * [C1] = [w8] </h2>
<h2> [B1] * [C2] = [w9] </h2>
<h2> [B2] * [C2] = [w10] </h2>
<h2> [B1] * [C3] = [w11] </h2>
<h2> [B2] * [C3] = [w12] </h2>