<a href="https://colab.research.google.com/github/InowaR/frame/blob/main/vectors_and_errors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
import numpy as np
import pandas as pd
b = np.array([1,2])
c = np.array([1,2])
a = np.array([1,2])
w = np.array([5,6,7,8])
b_tile = np.tile(b, 2)
c_repeat = np.repeat(c, 2)
a_tile = np.tile(a,2)
print(b_tile, '<---- b')
print(c_repeat, '<---- c')
print(a_tile, '<---- a')
b_new = np.ones(len(b))
b_new = b_new - b
b_new = np.tile(b_new, 2)
print(b_new, '<---- 1 - b')
w_new = np.split(w, 2)
print(w_new)
c_new = np.split(c_repeat, 2)
print (c_new)
c_weights = w * c_repeat
c_weights = np.split(c_weights, 2)
print(c_weights)
c_weights = pd.DataFrame(c_weights)
c_weights = c_weights.sum(axis=1)
c_weights.to_numpy()
c_weights = np.repeat(c_weights, 2)
c_w = c_weights.to_numpy()
print('---------Cw-------------')
print(c_w)

[1 2 1 2] <---- b
[1 1 2 2] <---- c
[1 2 1 2] <---- a
[ 0. -1.  0. -1.] <---- 1 - b
[array([5, 6]), array([7, 8])]
[array([1, 1]), array([2, 2])]
[array([5, 6]), array([14, 16])]
---------Cw-------------
[11 11 30 30]


In [69]:
c_repeat = pd.DataFrame(c_repeat)
print(c_repeat)
b_tile = pd.DataFrame(b_tile)
print(b_tile)
mul = c_repeat * b_tile
print('---------B*C(5,6,7,8)-------------')
print(mul)

   0
0  1
1  1
2  2
3  2
   0
0  1
1  2
2  1
3  2
---------B*C(5,6,7,8)-------------
   0
0  1
1  2
2  2
3  4


In [70]:
a_tile = pd.DataFrame(a_tile)
print(a_tile)
b_tile = pd.DataFrame(b_tile)
print(b_tile)

   0
0  1
1  2
2  1
3  2
   0
0  1
1  2
2  1
3  2


In [72]:
# errors = np.array([1,2])
# errors = pd.DataFrame(errors)
# print (errors)
# print('----------------------------------------')
# c = pd.DataFrame(c)
# print(c)
# print('----------------------------------------')
# ones = np.ones(len(w))
# ones = pd.DataFrame(ones)
# c_one = errors * c * (ones - c)
# c_one = c_one.to_numpy()
# print(c_one, '<---- dc * c * (1-с)')
# print('----------------------------------------'))