<a href="https://colab.research.google.com/github/InowaR/frame/blob/main/vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import numpy as np
import pandas as pd
b = np.array([1,2])
c = np.array([1,2])
a = np.array([1,2])
w = np.array([5,6,7,8])
b_tile = np.tile(b, 2)
c_repeat = np.repeat(c,2)
a_tile = np.tile(a,2)
print(b_tile)
print(c_repeat)
print(a_tile)
b_new = np.ones(len(b))
b_new = b_new - b
b_new = np.tile(b_new, 2)
print(b_new)
w_new = np.split(w, 2)
print(w_new)
c_new = np.split(c_repeat, 2)
print (c_new)
c_weights = w * c_repeat
c_weights = np.split(c_weights, 2)
print(c_weights)
c_weights = pd.DataFrame(c_weights)
c_weights = c_weights.sum(axis=1)
print(c_weights)

[1 2 1 2]
[1 1 2 2]
[1 2 1 2]
[ 0. -1.  0. -1.]
[array([5, 6]), array([7, 8])]
[array([1, 1]), array([2, 2])]
[array([5, 6]), array([14, 16])]
0    11
1    30
dtype: int64
